### ISSUE TITLE
Maximum length of filename path reached on Windows 10

### ISSUE THREAD

**Issue by baierst** [DataReply/persistable#3]
I cannot copy .pkl files created by persistable from another computer, due to a maximum length of filename path error in Windows 10. Apparently the filenames created by persistable are to long.

**Comment by aloosley** [comment]
This can occur when the total path is too long in the new Windows 10 environment.  The fix is to remove the Windows 10 path length constraint following this:

https://stackoverflow.com/questions/27680647/does-max-path-issue-still-exists-in-windows-10
